/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search across albums, artists, and genres by free-text query. */
    get: operations["Search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get autocomplete suggestions for the search box. */
    get: operations["GetSearchSuggestions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the current user's orders, paginated. */
    get: operations["GetOrders"];
    put?: never;
    /** Place an order from the current user's cart. */
    post: operations["CreateOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/orders/{orderNumber}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single order's detail by order number. */
    get: operations["GetOrderByNumber"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/genres": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all genres with each genre's album count. */
    get: operations["GetGenres"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/genres/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single genre's detail by its slug. */
    get: operations["GetGenreBySlug"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/decades": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all decades with each decade's album count. */
    get: operations["GetDecades"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/decades/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single decade's detail by its slug. */
    get: operations["GetDecadeBySlug"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cart/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replace the current user's cart contents with the given items. */
    post: operations["SyncCart"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cart": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the current user's cart contents. */
    get: operations["GetCart"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new user account. */
    post: operations["Register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a valid refresh token for a new access token and refresh token. */
    post: operations["Refresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invalidate the given refresh token. */
    post: operations["Logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate with email and password, returning an access token and refresh token. */
    post: operations["Login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the currently authenticated user's profile. */
    get: operations["GetCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/artists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all artists, alphabetically, with each artist's album count. */
    get: operations["GetArtists"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/artists/{sqid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single artist's detail and discography by sqid. */
    get: operations["GetArtistById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums/{sqid}/related": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get albums related to the given album, by shared genre, artist, or release date. */
    get: operations["GetRelatedAlbums"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums/cover-story": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get this week's featured staff-pick album. */
    get: operations["GetCoverStory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List albums with filtering, sorting, and pagination. */
    get: operations["GetAlbums"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums/{sqid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single album's full detail by its sqid. */
    get: operations["GetAlbumById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    AlbumDetailArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    AlbumDetailGenreResponse: {
      name: string;
      slug: string;
    };
    /**
     * @example {
     *       "sqid": "9pXqL2",
     *       "title": "Midnight Static",
     *       "titleSlug": "midnight-static",
     *       "description": "A shimmering slice of dream-pop, recorded over one rain-soaked winter in Bristol.",
     *       "label": "Harbour Light Records",
     *       "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *       "releaseDate": "1994-03-14",
     *       "priceInPence": 1899,
     *       "originalPriceInPence": 2299,
     *       "isNew": false,
     *       "isOnSale": true,
     *       "isStaffPick": true,
     *       "unitsInStock": 12,
     *       "isInStock": true,
     *       "artists": [
     *         {
     *           "sqid": "4mTb7K",
     *           "name": "The Coast Runners",
     *           "nameSlug": "the-coast-runners"
     *         }
     *       ],
     *       "genres": [
     *         {
     *           "name": "Dream Pop",
     *           "slug": "dream-pop"
     *         },
     *         {
     *           "name": "Shoegaze",
     *           "slug": "shoegaze"
     *         }
     *       ]
     *     }
     */
    AlbumDetailResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      description: null | string;
      label: null | string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["AlbumDetailArtistResponse"][];
      genres: components["schemas"]["AlbumDetailGenreResponse"][];
    };
    AlbumGenreResponse: {
      name: string;
      slug: string;
    };
    /**
     * @example {
     *       "sqid": "9pXqL2",
     *       "title": "Midnight Static",
     *       "titleSlug": "midnight-static",
     *       "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *       "releaseDate": "1994-03-14",
     *       "priceInPence": 1899,
     *       "originalPriceInPence": 2299,
     *       "isNew": false,
     *       "isOnSale": true,
     *       "isStaffPick": true,
     *       "unitsInStock": 12,
     *       "isInStock": true,
     *       "artists": [
     *         {
     *           "sqid": "4mTb7K",
     *           "name": "The Coast Runners",
     *           "nameSlug": "the-coast-runners"
     *         }
     *       ],
     *       "genres": [
     *         {
     *           "name": "Dream Pop",
     *           "slug": "dream-pop"
     *         },
     *         {
     *           "name": "Shoegaze",
     *           "slug": "shoegaze"
     *         }
     *       ]
     *     }
     */
    AlbumSummaryResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["AlbumArtistResponse"][];
      genres: components["schemas"]["AlbumGenreResponse"][];
    };
    ArtistAlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    ArtistAlbumResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["ArtistAlbumArtistResponse"][];
      genres: components["schemas"]["ArtistGenreResponse"][];
    };
    /**
     * @example {
     *       "sqid": "4mTb7K",
     *       "name": "The Coast Runners",
     *       "nameSlug": "the-coast-runners",
     *       "bio": "A four-piece formed in Brighton in 1991, blending jangly guitars with motorik rhythms.",
     *       "origin": "Brighton, UK",
     *       "type": "Group",
     *       "sinceYear": 1991,
     *       "imageUrl": "https://cdn.halcyonrecords.example/artists/the-coast-runners.jpg",
     *       "albumCount": 2,
     *       "genres": [
     *         {
     *           "name": "Dream Pop",
     *           "slug": "dream-pop"
     *         },
     *         {
     *           "name": "Shoegaze",
     *           "slug": "shoegaze"
     *         }
     *       ],
     *       "albums": [
     *         {
     *           "sqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *           "releaseDate": "1994-03-14",
     *           "priceInPence": 1899,
     *           "originalPriceInPence": 2299,
     *           "isNew": false,
     *           "isOnSale": true,
     *           "isStaffPick": true,
     *           "unitsInStock": 12,
     *           "isInStock": true,
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "genres": [
     *             {
     *               "name": "Dream Pop",
     *               "slug": "dream-pop"
     *             },
     *             {
     *               "name": "Shoegaze",
     *               "slug": "shoegaze"
     *             }
     *           ]
     *         },
     *         {
     *           "sqid": "7bWn4R",
     *           "title": "Harbour Lights",
     *           "titleSlug": "harbour-lights",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/harbour-lights.jpg",
     *           "releaseDate": "1997-09-02",
     *           "priceInPence": 1599,
     *           "originalPriceInPence": null,
     *           "isNew": true,
     *           "isOnSale": false,
     *           "isStaffPick": false,
     *           "unitsInStock": 34,
     *           "isInStock": true,
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "genres": [
     *             {
     *               "name": "Dream Pop",
     *               "slug": "dream-pop"
     *             }
     *           ]
     *         }
     *       ]
     *     }
     */
    ArtistDetailResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
      bio: null | string;
      origin: null | string;
      type: null | components["schemas"]["ArtistType"];
      /** Format: int32 */
      sinceYear: null | number;
      imageUrl: null | string;
      /** Format: int32 */
      albumCount: number;
      genres: components["schemas"]["ArtistGenreResponse"][];
      albums: components["schemas"]["ArtistAlbumResponse"][];
    };
    ArtistGenreResponse: {
      name: string;
      slug: string;
    };
    /**
     * @example {
     *       "sqid": "4mTb7K",
     *       "name": "The Coast Runners",
     *       "nameSlug": "the-coast-runners",
     *       "albumCount": 2
     *     }
     */
    ArtistListItemResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
      /** Format: int32 */
      albumCount: number;
    };
    /** @enum {unknown} */
    ArtistType:
      "Person" | "Group" | "Orchestra" | "Choir" | "Character" | "Other" | null;
    CartItemArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    /**
     * @example {
     *       "albumSqid": "9pXqL2",
     *       "title": "Midnight Static",
     *       "titleSlug": "midnight-static",
     *       "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *       "priceInPence": 1899,
     *       "originalPriceInPence": 2299,
     *       "quantity": 2,
     *       "unitsInStock": 12,
     *       "isInStock": true,
     *       "artists": [
     *         {
     *           "sqid": "4mTb7K",
     *           "name": "The Coast Runners",
     *           "nameSlug": "the-coast-runners"
     *         }
     *       ]
     *     }
     */
    CartItemResponse: {
      albumSqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      /** Format: int32 */
      quantity: number;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["CartItemArtistResponse"][];
    };
    CoverStoryArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    CoverStoryGenreResponse: {
      name: string;
      slug: string;
    };
    /**
     * @example {
     *       "sqid": "9pXqL2",
     *       "title": "Midnight Static",
     *       "titleSlug": "midnight-static",
     *       "description": "A shimmering slice of dream-pop, recorded over one rain-soaked winter in Bristol.",
     *       "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *       "releaseDate": "1994-03-14",
     *       "priceInPence": 1899,
     *       "originalPriceInPence": 2299,
     *       "isNew": false,
     *       "isOnSale": true,
     *       "isStaffPick": true,
     *       "unitsInStock": 12,
     *       "isInStock": true,
     *       "issueNumber": 47,
     *       "artists": [
     *         {
     *           "sqid": "4mTb7K",
     *           "name": "The Coast Runners",
     *           "nameSlug": "the-coast-runners"
     *         }
     *       ],
     *       "genres": [
     *         {
     *           "name": "Dream Pop",
     *           "slug": "dream-pop"
     *         },
     *         {
     *           "name": "Shoegaze",
     *           "slug": "shoegaze"
     *         }
     *       ]
     *     }
     */
    CoverStoryResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      description: null | string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      /** Format: int32 */
      issueNumber: number;
      artists: components["schemas"]["CoverStoryArtistResponse"][];
      genres: components["schemas"]["CoverStoryGenreResponse"][];
    };
    CreateOrderItemResponse: {
      albumSqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: int32 */
      quantity: number;
      /** Format: int32 */
      priceAtPurchaseInPence: number;
    };
    /**
     * @example {
     *       "contactFirstName": "John",
     *       "contactLastName": "Doe",
     *       "contactEmail": "john.doe@example.com",
     *       "idempotencyKey": "b3f1c2d4-5e6f-4a7b-8c9d-0e1f2a3b4c5d"
     *     }
     */
    CreateOrderRequest: {
      contactFirstName: string;
      contactLastName: string;
      contactEmail: string;
      /** Format: uuid */
      idempotencyKey: string;
    };
    /**
     * @example {
     *       "orderNumber": "HR-284917",
     *       "placedAt": "2026-01-14T16:32:00Z",
     *       "totalInPence": 3498,
     *       "items": [
     *         {
     *           "albumSqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *           "quantity": 2,
     *           "priceAtPurchaseInPence": 1899
     *         }
     *       ]
     *     }
     */
    CreateOrderResponse: {
      orderNumber: string;
      /** Format: date-time */
      placedAt: string;
      /** Format: int32 */
      totalInPence: number;
      items: components["schemas"]["CreateOrderItemResponse"][];
    };
    /**
     * @example {
     *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
     *       "email": "john.doe@example.com",
     *       "firstName": "John",
     *       "lastName": "Doe",
     *       "registeredAt": "2024-11-02T09:15:00Z"
     *     }
     */
    CurrentUserResponse: {
      /** Format: uuid */
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      /** Format: date-time */
      registeredAt: string;
    };
    /**
     * @example {
     *       "slug": "1990s",
     *       "label": "1990s",
     *       "startYear": 1990,
     *       "endYear": 1999,
     *       "description": "The decade that gave us shoegaze, trip-hop, and the rise of Britpop.",
     *       "imageUrl": "https://cdn.halcyonrecords.example/decades/1990s.jpg",
     *       "albumCount": 842
     *     }
     */
    DecadeDetailResponse: {
      slug: string;
      label: string;
      /** Format: int32 */
      startYear: null | number;
      /** Format: int32 */
      endYear: null | number;
      description: null | string;
      imageUrl: null | string;
      /** Format: int32 */
      albumCount: number;
    };
    /**
     * @example {
     *       "slug": "1990s",
     *       "label": "1990s",
     *       "startYear": 1990,
     *       "endYear": 1999,
     *       "imageUrl": "https://cdn.halcyonrecords.example/decades/1990s.jpg",
     *       "albumCount": 842
     *     }
     */
    DecadeListItemResponse: {
      slug: string;
      label: string;
      /** Format: int32 */
      startYear: null | number;
      /** Format: int32 */
      endYear: null | number;
      imageUrl: null | string;
      /** Format: int32 */
      albumCount: number;
    };
    DomainProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      code: string;
    };
    /**
     * @example {
     *       "name": "Dream Pop",
     *       "slug": "dream-pop",
     *       "description": "Hazy, reverb-drenched guitar pop that prioritises atmosphere over hooks.",
     *       "imageUrl": "https://cdn.halcyonrecords.example/genres/dream-pop.jpg",
     *       "albumCount": 128
     *     }
     */
    GenreDetailResponse: {
      name: string;
      slug: string;
      description: null | string;
      imageUrl: null | string;
      /** Format: int32 */
      albumCount: number;
    };
    /**
     * @example {
     *       "name": "Dream Pop",
     *       "slug": "dream-pop",
     *       "imageUrl": "https://cdn.halcyonrecords.example/genres/dream-pop.jpg",
     *       "albumCount": 128
     *     }
     */
    GenreListItemResponse: {
      name: string;
      slug: string;
      imageUrl: null | string;
      /** Format: int32 */
      albumCount: number;
    };
    HttpValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    /**
     * @example {
     *       "email": "john.doe@example.com",
     *       "password": "P@ssw0rd123!"
     *     }
     */
    LoginRequest: {
      email: string;
      password: string;
    };
    /**
     * @example {
     *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZmE4NWY2NCJ9.sIgnAtUrE",
     *       "refreshToken": "8f14e45f-ceea-4b6a-b8b7-4e2a1f6f1a2b",
     *       "expiresAt": "2026-01-14T17:32:00Z"
     *     }
     */
    LoginResponse: {
      accessToken: string;
      refreshToken: string;
      /** Format: date-time */
      expiresAt: string;
    };
    /**
     * @example {
     *       "refreshToken": "8f14e45f-ceea-4b6a-b8b7-4e2a1f6f1a2b"
     *     }
     */
    LogoutRequest: {
      refreshToken: string;
    };
    OrderDetailItemArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    OrderDetailItemResponse: {
      albumSqid: string;
      title: string;
      titleSlug: string;
      artists: components["schemas"]["OrderDetailItemArtistResponse"][];
      imageUrl: null | string;
      /** Format: int32 */
      quantity: number;
      /** Format: int32 */
      priceAtPurchaseInPence: number;
    };
    /**
     * @example {
     *       "orderNumber": "HR-284917",
     *       "placedAt": "2026-01-14T16:32:00Z",
     *       "status": "Placed",
     *       "contactFirstName": "John",
     *       "contactLastName": "Doe",
     *       "contactEmail": "john.doe@example.com",
     *       "totalInPence": 3498,
     *       "items": [
     *         {
     *           "albumSqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *           "quantity": 2,
     *           "priceAtPurchaseInPence": 1899
     *         }
     *       ]
     *     }
     */
    OrderDetailResponse: {
      orderNumber: string;
      /** Format: date-time */
      placedAt: string;
      status: components["schemas"]["OrderStatus"];
      contactFirstName: string;
      contactLastName: string;
      contactEmail: string;
      /** Format: int32 */
      totalInPence: number;
      items: components["schemas"]["OrderDetailItemResponse"][];
    };
    /** @enum {unknown} */
    OrderStatus: "Placed";
    OrderSummaryItemResponse: {
      albumSqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
    };
    /**
     * @example {
     *       "orderNumber": "HR-284917",
     *       "placedAt": "2026-01-14T16:32:00Z",
     *       "status": "Placed",
     *       "totalInPence": 3498,
     *       "items": [
     *         {
     *           "albumSqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg"
     *         }
     *       ]
     *     }
     */
    OrderSummaryResponse: {
      orderNumber: string;
      /** Format: date-time */
      placedAt: string;
      status: components["schemas"]["OrderStatus"];
      /** Format: int32 */
      totalInPence: number;
      items: components["schemas"]["OrderSummaryItemResponse"][];
    };
    /**
     * @example {
     *       "items": [
     *         {
     *           "sqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *           "releaseDate": "1994-03-14",
     *           "priceInPence": 1899,
     *           "originalPriceInPence": 2299,
     *           "isNew": false,
     *           "isOnSale": true,
     *           "isStaffPick": true,
     *           "unitsInStock": 12,
     *           "isInStock": true,
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "genres": [
     *             {
     *               "name": "Dream Pop",
     *               "slug": "dream-pop"
     *             },
     *             {
     *               "name": "Shoegaze",
     *               "slug": "shoegaze"
     *             }
     *           ]
     *         },
     *         {
     *           "sqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *           "releaseDate": "1994-03-14",
     *           "priceInPence": 1899,
     *           "originalPriceInPence": 2299,
     *           "isNew": false,
     *           "isOnSale": true,
     *           "isStaffPick": true,
     *           "unitsInStock": 12,
     *           "isInStock": true,
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "genres": [
     *             {
     *               "name": "Dream Pop",
     *               "slug": "dream-pop"
     *             },
     *             {
     *               "name": "Shoegaze",
     *               "slug": "shoegaze"
     *             }
     *           ]
     *         }
     *       ],
     *       "page": 1,
     *       "pageSize": 12,
     *       "totalCount": 2
     *     }
     */
    PagedResultOfAlbumSummaryResponse: {
      items: components["schemas"]["AlbumSummaryResponse"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      totalPages?: number;
    };
    /**
     * @example {
     *       "items": [
     *         {
     *           "orderNumber": "HR-284917",
     *           "placedAt": "2026-01-14T16:32:00Z",
     *           "status": "Placed",
     *           "totalInPence": 3498,
     *           "items": [
     *             {
     *               "albumSqid": "9pXqL2",
     *               "title": "Midnight Static",
     *               "titleSlug": "midnight-static",
     *               "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg"
     *             }
     *           ]
     *         },
     *         {
     *           "orderNumber": "HR-284917",
     *           "placedAt": "2026-01-14T16:32:00Z",
     *           "status": "Placed",
     *           "totalInPence": 3498,
     *           "items": [
     *             {
     *               "albumSqid": "9pXqL2",
     *               "title": "Midnight Static",
     *               "titleSlug": "midnight-static",
     *               "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg"
     *             }
     *           ]
     *         }
     *       ],
     *       "page": 1,
     *       "pageSize": 12,
     *       "totalCount": 2
     *     }
     */
    PagedResultOfOrderSummaryResponse: {
      items: components["schemas"]["OrderSummaryResponse"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      totalPages?: number;
    };
    /**
     * @example {
     *       "refreshToken": "8f14e45f-ceea-4b6a-b8b7-4e2a1f6f1a2b"
     *     }
     */
    RefreshRequest: {
      refreshToken: string;
    };
    /**
     * @example {
     *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzZmE4NWY2NCJ9.sIgnAtUrE",
     *       "refreshToken": "9a25f56g-dfeb-5c7b-c9c8-5f3b2g7g2b3c",
     *       "expiresAt": "2026-01-14T17:32:00Z"
     *     }
     */
    RefreshResponse: {
      accessToken: string;
      refreshToken: string;
      /** Format: date-time */
      expiresAt: string;
    };
    /**
     * @example {
     *       "firstName": "John",
     *       "lastName": "Doe",
     *       "email": "john.doe@example.com",
     *       "password": "P@ssw0rd123!"
     *     }
     */
    RegisterRequest: {
      firstName: string;
      lastName: string;
      email: string;
      password: string;
    };
    RelatedAlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    RelatedAlbumGenreResponse: {
      name: string;
      slug: string;
    };
    /**
     * @example {
     *       "sqid": "7bWn4R",
     *       "title": "Harbour Lights",
     *       "titleSlug": "harbour-lights",
     *       "imageUrl": "https://cdn.halcyonrecords.example/albums/harbour-lights.jpg",
     *       "releaseDate": "1997-09-02",
     *       "priceInPence": 1599,
     *       "originalPriceInPence": null,
     *       "isNew": true,
     *       "isOnSale": false,
     *       "isStaffPick": false,
     *       "unitsInStock": 34,
     *       "isInStock": true,
     *       "artists": [
     *         {
     *           "sqid": "4mTb7K",
     *           "name": "The Coast Runners",
     *           "nameSlug": "the-coast-runners"
     *         }
     *       ],
     *       "genres": [
     *         {
     *           "name": "Dream Pop",
     *           "slug": "dream-pop"
     *         }
     *       ]
     *     }
     */
    RelatedAlbumResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["RelatedAlbumArtistResponse"][];
      genres: components["schemas"]["RelatedAlbumGenreResponse"][];
    };
    SearchAlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    SearchAlbumGenreResponse: {
      name: string;
      slug: string;
    };
    SearchAlbumResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["SearchAlbumArtistResponse"][];
      genres: components["schemas"]["SearchAlbumGenreResponse"][];
    };
    /**
     * @example {
     *       "bestMatches": [
     *         {
     *           "sqid": "9pXqL2",
     *           "title": "Midnight Static",
     *           "titleSlug": "midnight-static",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/midnight-static.jpg",
     *           "releaseDate": "1994-03-14",
     *           "priceInPence": 1899,
     *           "originalPriceInPence": 2299,
     *           "isNew": false,
     *           "isOnSale": true,
     *           "isStaffPick": true,
     *           "unitsInStock": 12,
     *           "isInStock": true,
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "genres": [
     *             {
     *               "name": "Dream Pop",
     *               "slug": "dream-pop"
     *             },
     *             {
     *               "name": "Shoegaze",
     *               "slug": "shoegaze"
     *             }
     *           ]
     *         }
     *       ],
     *       "suggestions": [
     *         {
     *           "sqid": "7bWn4R",
     *           "title": "Harbour Lights",
     *           "titleSlug": "harbour-lights",
     *           "imageUrl": "https://cdn.halcyonrecords.example/albums/harbour-lights.jpg",
     *           "releaseDate": "1997-09-02",
     *           "priceInPence": 1599,
     *           "originalPriceInPence": null,
     *           "isNew": true,
     *           "isOnSale": false,
     *           "isStaffPick": false,
     *           "unitsInStock": 34,
     *           "isInStock": true,
     *           "artists": [
     *             {
     *               "sqid": "4mTb7K",
     *               "name": "The Coast Runners",
     *               "nameSlug": "the-coast-runners"
     *             }
     *           ],
     *           "genres": [
     *             {
     *               "name": "Dream Pop",
     *               "slug": "dream-pop"
     *             }
     *           ]
     *         }
     *       ],
     *       "suggestedTerms": [
     *         "midnight",
     *         "dream pop",
     *         "shoegaze"
     *       ],
     *       "totalCount": 1
     *     }
     */
    SearchResponse: {
      bestMatches: components["schemas"]["SearchAlbumResponse"][];
      suggestions: components["schemas"]["SearchAlbumResponse"][];
      suggestedTerms: string[];
      /** Format: int32 */
      totalCount: number;
    };
    SyncCartItemRequest: {
      albumSqid: string;
      /** Format: int32 */
      quantity: number;
    };
    /**
     * @example {
     *       "items": [
     *         {
     *           "albumSqid": "9pXqL2",
     *           "quantity": 2
     *         },
     *         {
     *           "albumSqid": "7bWn4R",
     *           "quantity": 1
     *         }
     *       ]
     *     }
     */
    SyncCartRequest: {
      items: components["schemas"]["SyncCartItemRequest"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  Search: {
    parameters: {
      query?: {
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetSearchSuggestions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetOrders: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedResultOfOrderSummaryResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  CreateOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrderRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreateOrderResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetOrderByNumber: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderNumber: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderDetailResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetGenres: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenreListItemResponse"][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetGenreBySlug: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GenreDetailResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetDecades: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecadeListItemResponse"][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetDecadeBySlug: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecadeDetailResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  SyncCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SyncCartRequest"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CartItemResponse"][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  Register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  Refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefreshResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  Logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  Login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetArtists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtistListItemResponse"][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetArtistById: {
    parameters: {
      query?: {
        sort?: "NewestFirst" | "OldestFirst" | "PriceAsc" | "PriceDesc";
      };
      header?: never;
      path: {
        sqid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtistDetailResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetRelatedAlbums: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sqid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelatedAlbumResponse"][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetCoverStory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoverStoryResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetAlbums: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        isNew?: boolean;
        isOnSale?: boolean;
        isStaffPick?: boolean;
        inStock?: boolean;
        genres?: string[];
        startYear?: number;
        endYear?: number;
        sort?:
          | "NewestFirst"
          | "OldestFirst"
          | "PriceAsc"
          | "PriceDesc"
          | "ArtistAZ"
          | "ArtistZA";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedResultOfAlbumSummaryResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
  GetAlbumById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sqid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlbumDetailResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["DomainProblemDetails"];
        };
      };
      /** @description Request Timeout */
      408: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
          };
        };
      };
    };
  };
}
