/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/artists": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetArtists"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/artists/{sqid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetArtistById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums/{sqid}/related": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetRelatedAlbums"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums/cover-story": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetCoverStory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetAlbums"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/albums/{sqid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["GetAlbumById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    AlbumDetailArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    AlbumDetailGenreResponse: {
      name: string;
      slug: string;
    };
    AlbumDetailResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      description: null | string;
      label: null | string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      /** Format: int32 */
      unitsInStock: number;
      isInStock: boolean;
      artists: components["schemas"]["AlbumDetailArtistResponse"][];
      genres: components["schemas"]["AlbumDetailGenreResponse"][];
    };
    AlbumGenreResponse: {
      name: string;
      slug: string;
    };
    AlbumSummaryResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      isInStock: boolean;
      artists: components["schemas"]["AlbumArtistResponse"][];
      genres: components["schemas"]["AlbumGenreResponse"][];
    };
    ArtistAlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    ArtistAlbumResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      isInStock: boolean;
      artists: components["schemas"]["ArtistAlbumArtistResponse"][];
      genres: components["schemas"]["ArtistGenreResponse"][];
    };
    ArtistDetailResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
      bio: null | string;
      origin: null | string;
      type: null | components["schemas"]["ArtistType"];
      /** Format: int32 */
      sinceYear: null | number;
      imageUrl: null | string;
      /** Format: int32 */
      albumCount: number;
      genres: components["schemas"]["ArtistGenreResponse"][];
      albums: components["schemas"]["ArtistAlbumResponse"][];
    };
    ArtistGenreResponse: {
      name: string;
      slug: string;
    };
    ArtistListItemResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
      /** Format: int32 */
      albumCount: number;
    };
    ArtistType: number;
    CoverStoryArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    CoverStoryGenreResponse: {
      name: string;
      slug: string;
    };
    CoverStoryResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      description: null | string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      isInStock: boolean;
      /** Format: int32 */
      issueNumber: number;
      artists: components["schemas"]["CoverStoryArtistResponse"][];
      genres: components["schemas"]["CoverStoryGenreResponse"][];
    };
    HttpValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    PagedResultOfAlbumSummaryResponse: {
      items: components["schemas"]["AlbumSummaryResponse"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      totalPages?: number;
    };
    RelatedAlbumArtistResponse: {
      sqid: string;
      name: string;
      nameSlug: string;
    };
    RelatedAlbumGenreResponse: {
      name: string;
      slug: string;
    };
    RelatedAlbumResponse: {
      sqid: string;
      title: string;
      titleSlug: string;
      imageUrl: null | string;
      /** Format: date */
      releaseDate: null | string;
      /** Format: int32 */
      priceInPence: number;
      /** Format: int32 */
      originalPriceInPence: null | number;
      isNew: boolean;
      isOnSale: boolean;
      isStaffPick: boolean;
      isInStock: boolean;
      artists: components["schemas"]["RelatedAlbumArtistResponse"][];
      genres: components["schemas"]["RelatedAlbumGenreResponse"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetArtists: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtistListItemResponse"][];
        };
      };
    };
  };
  GetArtistById: {
    parameters: {
      query?: {
        sort?: string;
      };
      header?: never;
      path: {
        sqid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtistDetailResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
    };
  };
  GetRelatedAlbums: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sqid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelatedAlbumResponse"][];
        };
      };
    };
  };
  GetCoverStory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoverStoryResponse"];
        };
      };
    };
  };
  GetAlbums: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        isNew?: boolean;
        isOnSale?: boolean;
        isStaffPick?: boolean;
        inStock?: boolean;
        genres?: string[];
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PagedResultOfAlbumSummaryResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
    };
  };
  GetAlbumById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sqid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlbumDetailResponse"];
        };
      };
    };
  };
}
